name: my_flutter_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any  # Let it choose the latest compatible version
  firebase_auth: any  # Let it choose the latest compatible version
  cloud_firestore: any  # Let it choose the latest compatible version
  cupertino_icons: any  # Let it choose the latest compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # This can remain as is since you want the latest

flutter:
  uses-material-design: true

  assets:
    - assets/main_logo.png
    - assets/Rectangle25.png
    - assets/Image2.png
    - assets/Icons8play501.png
    - assets/Icons8about241.png
    - assets/Icons8settings5011.png
    - assets/Icons8home481.png
    - assets/Icons8usericon241.png
    - assets/ragachikitsalogo.png
